"""add term deadlines

Revision ID: ec4136529f9c
Revises: 
Create Date: 2026-09-29 10:21:04.912953

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'ec4136529f9c'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('school_classes', schema=None) as batch_op:
        batch_op.add_column(sa.Column('level_group', sa.String(length=30), nullable=True))

    with op.batch_alter_table('staff', schema=None) as batch_op:
        batch_op.add_column(sa.Column('photo_path', sa.String(length=255), nullable=True))

    with op.batch_alter_table('staff_attendance', schema=None) as batch_op:
        batch_op.add_column(sa.Column('check_in_lat', sa.Float(), nullable=True))
        batch_op.add_column(sa.Column('check_in_lng', sa.Float(), nullable=True))
        batch_op.add_column(sa.Column('check_in_accuracy_m', sa.Float(), nullable=True))
        batch_op.add_column(sa.Column('check_in_distance_m', sa.Float(), nullable=True))
        batch_op.add_column(sa.Column('check_in_verified', sa.Boolean(), nullable=True))
        batch_op.add_column(sa.Column('check_out_lat', sa.Float(), nullable=True))
        batch_op.add_column(sa.Column('check_out_lng', sa.Float(), nullable=True))
        batch_op.add_column(sa.Column('check_out_accuracy_m', sa.Float(), nullable=True))
        batch_op.add_column(sa.Column('check_out_distance_m', sa.Float(), nullable=True))
        batch_op.add_column(sa.Column('check_out_verified', sa.Boolean(), nullable=True))

    with op.batch_alter_table('terms', schema=None) as batch_op:
        batch_op.add_column(sa.Column('result_entry_deadline', sa.Date(), nullable=True))
        batch_op.add_column(sa.Column('lesson_plan_deadline', sa.Date(), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('terms', schema=None) as batch_op:
        batch_op.drop_column('lesson_plan_deadline')
        batch_op.drop_column('result_entry_deadline')

    with op.batch_alter_table('staff_attendance', schema=None) as batch_op:
        batch_op.drop_column('check_out_verified')
        batch_op.drop_column('check_out_distance_m')
        batch_op.drop_column('check_out_accuracy_m')
        batch_op.drop_column('check_out_lng')
        batch_op.drop_column('check_out_lat')
        batch_op.drop_column('check_in_verified')
        batch_op.drop_column('check_in_distance_m')
        batch_op.drop_column('check_in_accuracy_m')
        batch_op.drop_column('check_in_lng')
        batch_op.drop_column('check_in_lat')

    with op.batch_alter_table('staff', schema=None) as batch_op:
        batch_op.drop_column('photo_path')

    with op.batch_alter_table('school_classes', schema=None) as batch_op:
        batch_op.drop_column('level_group')

    # ### end Alembic commands ###
